### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/testgerrit#29]
test

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**gerrit issue hook test** https://gerrit.sqlalchemy.org/c/sqlalchemy/testgerrit/+/4642

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fix from ryzen1 test gerrit 3.5.6** http://ryzen1:8081/c/sqlalchemy/testgerrit/+/4641

**Comment by zzzeek** [comment]
fixed, until the next gerrit upgrade
